# Generated by Django 5.2.1 on 2025-06-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('cost_price', models.FloatField()),
                ('sales_price', models.FloatField()),
                ('display_name', models.CharField(max_length=400)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('barcode', models.CharField(blank=True, max_length=20, null=True)),
                ('unit_of_measurement', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
