# Generated by Django 5.2.1 on 2025-06-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_store', '0003_product_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
