# Generated by Django 5.2.1 on 2025-06-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_store', '0004_alter_product_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
