# Generated by Django 5.2.1 on 2025-06-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_store', '0005_alter_product_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='avail_qty',
            field=models.IntegerField(default=1),
        ),
    ]
