# Generated by Django 5.2.1 on 2025-06-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_store', '0009_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
