# Generated by Django 5.2.1 on 2025-06-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_store', '0012_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='payment_type',
            field=models.CharField(choices=[('upi', 'UP['), ('debit_card', 'Confirmed'), ('phonepe', 'Phonepe'), ('gpay', 'Gpay'), ('net_banking', 'Net Banking'), ('cod', 'Cash on Delivery')], default='upi'),
        ),
    ]
