# Generated by Django 5.2.1 on 2025-06-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_store', '0013_payments_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_type',
            field=models.CharField(choices=[('upi', 'UPI'), ('debit_card', 'Debit Card'), ('phonepe', 'PhonePe'), ('gpay', 'GPay'), ('net_banking', 'Net Banking'), ('cod', 'Cash on Delivery')], default='upi'),
        ),
    ]
