# Generated by Django 5.2.1 on 2025-06-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_store', '0015_payments_payment_date_payments_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='draft', max_length=100),
        ),
        migrations.AlterField(
            model_name='payments',
            name='payment_type',
            field=models.CharField(choices=[('upi', 'UPI'), ('debit_card', 'Debit Card'), ('phonepe', 'PhonePe'), ('gpay', 'GPay'), ('net_banking', 'Net Banking'), ('cod', 'Cash on Delivery')], default='upi', max_length=100),
        ),
    ]
